// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session_02.Contexts;

#nullable disable

namespace Session_02.Migrations.HospitalDb
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20250927165526_Create HospitalDbWithIt'sTablesAndRelations")]
    partial class CreateHospitalDbWithItsTablesAndRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Session_02.HospitalModels.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Drug_Brand", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code", "Brand");

                    b.ToTable("DrugBrands");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Drugs", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Nurse", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ward_Id")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.HasIndex("Ward_Id");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Nurse_Drug_Patient", b =>
                {
                    b.Property<int>("Nur_Num")
                        .HasColumnType("int");

                    b.Property<int>("Drug_code")
                        .HasColumnType("int");

                    b.Property<int>("Pat_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Nur_Num", "Drug_code", "Pat_Id");

                    b.HasIndex("Drug_code");

                    b.HasIndex("Pat_Id");

                    b.ToTable("NurseDrugPatients");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Con_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ward_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Con_Id");

                    b.HasIndex("Ward_Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Patient_Con", b =>
                {
                    b.Property<int>("Con_Id")
                        .HasColumnType("int");

                    b.Property<int>("Pat_Id")
                        .HasColumnType("int");

                    b.HasKey("Con_Id", "Pat_Id");

                    b.HasIndex("Pat_Id");

                    b.ToTable("PatientCons");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nurse_Num")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nurse_Num");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Drug_Brand", b =>
                {
                    b.HasOne("Session_02.HospitalModels.Drugs", "Drug")
                        .WithMany("DrugBrands")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Nurse", b =>
                {
                    b.HasOne("Session_02.HospitalModels.Ward", "Ward")
                        .WithMany("Nurses")
                        .HasForeignKey("Ward_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Nurse_Drug_Patient", b =>
                {
                    b.HasOne("Session_02.HospitalModels.Drugs", "Drug")
                        .WithMany("NurseDrugRecords")
                        .HasForeignKey("Drug_code")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session_02.HospitalModels.Nurse", "Nurse")
                        .WithMany("NurseDrugRecords")
                        .HasForeignKey("Nur_Num")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session_02.HospitalModels.Patient", "Patient")
                        .WithMany("NurseDrugPatients")
                        .HasForeignKey("Pat_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Patient", b =>
                {
                    b.HasOne("Session_02.HospitalModels.Consultant", "Consultant")
                        .WithMany("Patients")
                        .HasForeignKey("Con_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Session_02.HospitalModels.Ward", "Ward")
                        .WithMany("Patients")
                        .HasForeignKey("Ward_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Patient_Con", b =>
                {
                    b.HasOne("Session_02.HospitalModels.Consultant", "Consultant")
                        .WithMany("Patient_Cons")
                        .HasForeignKey("Con_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session_02.HospitalModels.Patient", "Patient")
                        .WithMany("Patient_Cons")
                        .HasForeignKey("Pat_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Ward", b =>
                {
                    b.HasOne("Session_02.HospitalModels.Nurse", "WardManager")
                        .WithMany("ManagedWards")
                        .HasForeignKey("Nurse_Num")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WardManager");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Consultant", b =>
                {
                    b.Navigation("Patient_Cons");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Drugs", b =>
                {
                    b.Navigation("DrugBrands");

                    b.Navigation("NurseDrugRecords");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Nurse", b =>
                {
                    b.Navigation("ManagedWards");

                    b.Navigation("NurseDrugRecords");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Patient", b =>
                {
                    b.Navigation("NurseDrugPatients");

                    b.Navigation("Patient_Cons");
                });

            modelBuilder.Entity("Session_02.HospitalModels.Ward", b =>
                {
                    b.Navigation("Nurses");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
