// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session_02.Contexts;

#nullable disable

namespace Session_02.Migrations.MusicianMapDb
{
    [DbContext(typeof(MusicianMapDbContext))]
    [Migration("20250927172040_CreateMusicianMapDbWithIt'sTablesAndRelations")]
    partial class CreateMusicianMapDbWithItsTablesAndRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Session_02.MusicianMapModels.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mus_Id")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Mus_Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Album_Song", b =>
                {
                    b.Property<string>("Song_Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Album_Id")
                        .HasColumnType("int");

                    b.HasKey("Song_Title");

                    b.HasIndex("Album_Id");

                    b.ToTable("AlbumSongs");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Instrument", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Mus_Instrument", b =>
                {
                    b.Property<int>("Mus_Id")
                        .HasColumnType("int");

                    b.Property<string>("Inst_Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Mus_Id", "Inst_Name");

                    b.HasIndex("Inst_Name");

                    b.ToTable("MusInstruments");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Mus_Song", b =>
                {
                    b.Property<int>("Mus_Id")
                        .HasColumnType("int");

                    b.Property<string>("Song_Tittle")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Mus_Id", "Song_Tittle");

                    b.HasIndex("Song_Tittle");

                    b.ToTable("MusSongs");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar");

                    b.Property<string>("Ph_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Song", b =>
                {
                    b.Property<string>("Tittle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tittle");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Album", b =>
                {
                    b.HasOne("Session_02.MusicianMapModels.Musician", "Musician")
                        .WithMany("Albums")
                        .HasForeignKey("Mus_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Album_Song", b =>
                {
                    b.HasOne("Session_02.MusicianMapModels.Album", "Album")
                        .WithMany("AlbumSongs")
                        .HasForeignKey("Album_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Session_02.MusicianMapModels.Song", "Song")
                        .WithMany("AlbumSongs")
                        .HasForeignKey("Song_Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Mus_Instrument", b =>
                {
                    b.HasOne("Session_02.MusicianMapModels.Instrument", "Instrument")
                        .WithMany("MusInstruments")
                        .HasForeignKey("Inst_Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Session_02.MusicianMapModels.Musician", "Musician")
                        .WithMany("MusInstruments")
                        .HasForeignKey("Mus_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Mus_Song", b =>
                {
                    b.HasOne("Session_02.MusicianMapModels.Musician", "Musician")
                        .WithMany("MusSongs")
                        .HasForeignKey("Mus_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Session_02.MusicianMapModels.Song", "Song")
                        .WithMany("MusSongs")
                        .HasForeignKey("Song_Tittle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Album", b =>
                {
                    b.Navigation("AlbumSongs");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Instrument", b =>
                {
                    b.Navigation("MusInstruments");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Musician", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("MusInstruments");

                    b.Navigation("MusSongs");
                });

            modelBuilder.Entity("Session_02.MusicianMapModels.Song", b =>
                {
                    b.Navigation("AlbumSongs");

                    b.Navigation("MusSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
