// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session_02.Contexts;

#nullable disable

namespace Session_02.Migrations.SalesDb
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Session_02.SalesModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Off_Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Off_Number");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Session_02.SalesModels.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Session_02.SalesModels.PropOwner", b =>
                {
                    b.Property<int>("Own_Id")
                        .HasColumnType("int");

                    b.Property<int>("Prop_Id")
                        .HasColumnType("int");

                    b.Property<double>("Precent")
                        .HasColumnType("float");

                    b.HasKey("Own_Id", "Prop_Id");

                    b.HasIndex("Prop_Id");

                    b.ToTable("PropOwners");
                });

            modelBuilder.Entity("Session_02.SalesModels.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Off_Number")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Off_Number");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Session_02.SalesModels.SalesOffice", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<int>("Emp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Number");

                    b.HasIndex("Emp_Id");

                    b.ToTable("SalesOffices");
                });

            modelBuilder.Entity("Session_02.SalesModels.Employee", b =>
                {
                    b.HasOne("Session_02.SalesModels.SalesOffice", "Office")
                        .WithMany()
                        .HasForeignKey("Off_Number")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Session_02.SalesModels.PropOwner", b =>
                {
                    b.HasOne("Session_02.SalesModels.Owner", "Owner")
                        .WithMany("PropertyOwners")
                        .HasForeignKey("Own_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session_02.SalesModels.Property", "Property")
                        .WithMany("PropertyOwners")
                        .HasForeignKey("Prop_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Session_02.SalesModels.Property", b =>
                {
                    b.HasOne("Session_02.SalesModels.SalesOffice", "SalesOffice")
                        .WithMany("Properties")
                        .HasForeignKey("Off_Number")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SalesOffice");
                });

            modelBuilder.Entity("Session_02.SalesModels.SalesOffice", b =>
                {
                    b.HasOne("Session_02.SalesModels.Employee", "Manager")
                        .WithMany("ManagedOffices")
                        .HasForeignKey("Emp_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Session_02.SalesModels.Employee", b =>
                {
                    b.Navigation("ManagedOffices");
                });

            modelBuilder.Entity("Session_02.SalesModels.Owner", b =>
                {
                    b.Navigation("PropertyOwners");
                });

            modelBuilder.Entity("Session_02.SalesModels.Property", b =>
                {
                    b.Navigation("PropertyOwners");
                });

            modelBuilder.Entity("Session_02.SalesModels.SalesOffice", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
